### ISSUE TITLE
KeyError

### ISSUE THREAD

**Issue by leenaraz** [JaywongWang/DenseVideoCaptioning#9]
When i run python train.py i receive the following error.
python train.py 
work_dir checkpoints/1 exists! Pls check it.
2019-03-11 19:12:17.115490: I tensorflow/core/platform/cpu_feature_guard.cc:141] Your CPU supports instructions that this TensorFlow binary was not compiled to use: AVX2 FMA
2019-03-11 19:12:17.137557: I tensorflow/core/platform/profile_utils/cpu_utils.cc:94] CPU Frequency: 1992000000 Hz
2019-03-11 19:12:17.138025: I tensorflow/compiler/xla/service/service.cc:150] XLA service 0x561a1826ee40 executing computations on platform Host. Devices:
2019-03-11 19:12:17.138077: I tensorflow/compiler/xla/service/service.cc:158]   StreamExecutor device (0): <undefined>, <undefined>
Load data ...
Traceback (most recent call last):
  File "train.py", line 541, in <module>
    train(options)
  File "train.py", line 262, in train
    data_provision = DataProvision(options)
  File "/home/leena/mainproject/DenseVideoCaptioning/data_provider.py", line 23, in __init__
    np.random.seed(options['random_seed'])
KeyError: 'random_seed'

**Comment by JaywongWang** [comment]
I have corrected the error by adding "random_seed" in opt.py.

**Comment by leenaraz** [comment]
Thanks. That fixed it!
